### ISSUE TITLE
Error : cp: cannot create regular file

### ISSUE THREAD

**Issue by PLoic** [djosephsen/skinnywhale#2]
Hi,

I just found your tool and he looks great, but when I'm using it with my container, I get this and I do not understand why.

DEBUG:: rundir is /tmp/skinnyRun7244
DEBUG:: layer is aaa079a8544e3cb00d6475a9df4dd9b152f555796c1cedc2e7a5db7785da07cb
DEBUG:: LPATH is /var/lib/docker/aufs/diff/aaa079a8544e3cb00d6475a9df4dd9b152f555796c1cedc2e7a5db7785da07cb
DEBUG:: cp -nv /tmp/skinnyRun7244/FULL//usr/bin/ldd /tmp/skinnyRun7244/DIFF/usr/bin
‘/tmp/skinnyRun7244/FULL//usr/bin/ldd’ -> ‘/tmp/skinnyRun7244/DIFF/usr/bin’
cp: cannot create regular file ‘/tmp/skinnyRun7244/DIFF/usr/bin’: No such file or directory
DEBUG:: DEPENDENCIES is 
DEBUG:: BRUTELIB enabled! Copying over /tmp/skinnyRun7244/FULL/lib
DEBUG:: BRUTEUSRLIB enabled! Copying over /tmp/skinnyRun7244/FULL/lib
DEBUG:: tar -cv . | docker import - skinny_aaa079a8544e

Thanks in advance for your answer.

**Comment by djosephsen** [comment]
well it _looks_ to me like maybe you don't have a /tmp directory? Do you have a /tmp directory?

**Comment by jefflaplante** [comment]
I get the same above error. I have a /tmp directory on my host. Do notice there's a double // in the cp command's source path. I haven't dug into what part of the path is missing there.
